apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user1-foo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aiit-koyama-pbl-2025/argocd-apps.git
    targetRevision: HEAD
    path: apps/user1-foo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
